In [1]:
import numpy as np

In [3]:
arr = np.random.random((3,4))
arr

array([[0.89598023, 0.59735491, 0.34564375, 0.52573298],
       [0.59507174, 0.12484291, 0.48135032, 0.47031629],
       [0.65911465, 0.24270011, 0.20216152, 0.89009307]])

In [5]:
arr = np.random.randint(10,100,(4,5))
arr

array([[51, 58, 64, 47, 75],
       [18, 35, 77, 98, 69],
       [87, 36, 51, 76, 62],
       [74, 30, 69, 75, 80]], dtype=int32)

In [8]:
d = np.linspace(10,20,3)
d

array([10., 15., 20.])

In [10]:
arr = np.arange(10,20,3)
arr

array([10, 13, 16, 19])

In [12]:
l = [1,2,3,4]

ar = np.asarray(l)
ar

array([1, 2, 3, 4])

In [28]:
arr = np.random.randint(1,50,(3,3))
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)
arr

2
(3, 3)
9
int32


array([[11, 30, 20],
       [26, 13, 10],
       [ 3, 15, 13]], dtype=int32)

In [20]:
l = [1,2,3] 
l2 = [4,5,6]
print(l+l2)

a = np.asarray(l)
b = np.asanyarray(l2)

print(a+b)

[1, 2, 3, 4, 5, 6]
[5 7 9]


In [23]:
print(np.add(a,b))
print(np.subtract(a,b))

[5 7 9]
[-3 -3 -3]


In [29]:
arr =  arr.T
arr

array([[11, 26,  3],
       [30, 13, 15],
       [20, 10, 13]], dtype=int32)

In [30]:
c = arr.reshape(9,1)
c

array([[11],
       [26],
       [ 3],
       [30],
       [13],
       [15],
       [20],
       [10],
       [13]], dtype=int32)

In [31]:
c = arr.reshape(9,)
c

array([11, 26,  3, 30, 13, 15, 20, 10, 13], dtype=int32)